id: IED7DF49D
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T10:32:37.742459'
last_modified: '2022-06-19T10:32:37.742470'
parser: null
source_metadata:
  title: Hagiography of Sa skya bdag chen Blo gros rgyal mtshan (1444–1495); Lamdre
    Lobshe, vol. kha, title no. 2
  author: ཚར་ཆེན་བློ་གསལ་རྒྱ་མཚོ།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-08-21);
    converted from external file, unrevised, spell-checked, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), Kunga Dorje (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/380
  bases:
    a915:
      title: Hagiography of Sa skya bdag chen Blo gros rgyal mtshan (1444–1495); Lamdre
        Lobshe, vol. kha, title no. 2
      order: 1
      base_file: a915.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
